SHARED_LIB_DEPS =
SHARED_APP_DEPS =
STATIC_APP_DEPS =

COMMON_LOBJS 	= $(COMMON_SRCS:.c=.lo)
COMMON_OBJS 	= $(COMMON_SRCS:.c=.o)

ARCH_LOBJS 	= $(ARCH_SRCS:.c=.lo)
ARCH_OBJS 	= $(ARCH_SRCS:.c=.o)

SHARED_OBJS 	= $(COMMON_LOBJS) $(ARCH_LOBJS)
STATIC_OBJS 	= $(COMMON_OBJS)  $(ARCH_OBJS)

SHARED_LIB 	= $(LIBDIR)/$(OS_LIB_PREFIX)$(PACKAGE)$(OS_LIB_SUFFIX)
STATIC_LIB 	= $(LIBDIR)/$(OS_LIB_PREFIX)$(PACKAGE)$(OS_ARCHIVE_EXT)
SHARED_IMPLIB 	= $(LIBDIR)/$(OS_LIB_PREFIX)$(PACKAGE)$(OS_IMPLIB_EXT)

CFLAGS		= $(CFLAGS_DEBUG)  $(CFLAGS_CONFIG)  $(CFLAGS_SYSROOT) \
		   $(CFLAGS_COMMON) $(CFLAGS_CMDLINE) $(CFLAGS_HOST) 	\
		   $(CFLAGS_PATH)

CFLAGS_SHARED 	= $(CFLAGS) $(CFLAGS_PIC) $(CFLAGS_SHARED_ATTR)
CFLAGS_STATIC 	= $(CFLAGS) $(CFLAGS_OBJ) $(CFLAGS_STATIC_ATTR)

LDFLAGS_SHARED	= $(LDFLAGS_DEBUG)   $(LDFLAGS_CONFIG)  $(LDFLAGS_SYSROOT) \
		   $(LDFLAGS_COMMON)  $(LDFLAGS_CMDLINE) $(LDFLAGS_HOST)    \
		   $(LDFLAGS_PATH)    $(SHARED_LIB_DEPS) $(LDFLAGS_LAST)

LDFLAGS_STATIC	= $(LDFLAGS_DEBUG)   $(LDFLAGS_CONFIG)  $(LDFLAGS_SYSROOT) \
		   $(LDFLAGS_COMMON)  $(LDFLAGS_CMDLINE) $(LDFLAGS_HOST)    \
		   $(LDFLAGS_PATH)    $(STATIC_APP_DEPS) $(LDFLAGS_LAST)
